name: Asset size

on: [workflow_dispatch]

jobs:
  compare:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: chrysanthos/simple-asset-size-reporter@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["dist/*.js"]'
          with-same: "false"
          build-assets: "npm run install-build"
