name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    timeout-minutes: 10
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        if: runner.os == 'Windows'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pin npm version
        run: npm install -g npm@11.10.0
      - name: Cache node modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: v2-${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - run: npm ci
      - run: npm test
        env:
          CI: true

  benchmark:
    timeout-minutes: 15
    name: Measure performance impact of changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      - name: Pin npm version
        run: npm install -g npm@11.10.0
      - name: Cache node modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: v2-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-npm-
      - run: npm ci
      - run: npm run benchmark
        env:
          CI: true

  typescript:
    timeout-minutes: 15
    name: Ensure typescript compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
      - name: Pin npm version
        run: npm install -g npm@11.10.0
      - name: Cache node modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: v2-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-npm-
      - run: npm ci
      - run: npx tsc -p tsconfig.check.json
        env:
          CI: true
